# Generated by Django 4.2.26 on 2025-11-20 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentenrollment",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"roles__name": "STUDENT"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="class_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.class"
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"roles__name": "STUDENT"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.subject"
            ),
        ),
        migrations.AddField(
            model_name="classassignment",
            name="class_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.class"
            ),
        ),
        migrations.AddField(
            model_name="classassignment",
            name="school_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.schoolyear"
            ),
        ),
        migrations.AddField(
            model_name="classassignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.subject"
            ),
        ),
        migrations.AddField(
            model_name="classassignment",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"roles__name": "TEACHER"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="school_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.schoolyear"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="class_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.class"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="recorded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances_recorded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"roles__name": "STUDENT"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentenrollment",
            unique_together={("student", "class_obj", "school_year")},
        ),
        migrations.AlterUniqueTogether(
            name="classassignment",
            unique_together={("teacher", "subject", "class_obj", "school_year")},
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "class_obj", "date", "period")},
        ),
    ]
