# Generated by Django 4.2.26 on 2025-11-20 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academic", "0002_initial"),
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="academicsetting",
            name="school_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.schoolyear"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academicsetting",
            unique_together={("school_year", "setting_key")},
        ),
    ]
